MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "models/resnet50_sin.pth"
  FORCE_WEIGHT: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: 1
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ASPECT_RATIOS: (0.8, 1.6, 2.3)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 11
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: False
  SEED: 233
DATASETS:
  TRAIN: ("tianchi_xray_with_normal_in_coco",)
  TEST: ("tianchi_xray_eval_no_normal_bbox_in_coco",)
  # TEST: ("tianchi_xray_test_a_in_coco",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 16
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, 54000)
  MAX_ITER: 60000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 400
INPUT:
  MIXUP: True
  NO_MIXUP_ITERS: 12000
  TO_BGR255: False
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
TEST:
  IMS_PER_BATCH: 16
OUTPUT_DIR: "logs/tianchi_xray/mask_rcnn_R_50_FPN_from_resnet_sin"
