MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "models/detnet_with_fpn_and_rpn_head.pth"
  FORCE_WEIGHT: True
  BACKBONE:
    CONV_BODY: "D-59-D-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
  RPN:
    USE_FPN: True
    ASPECT_RATIOS: (0.5, 0.92, 1.5)
    ANCHOR_STRIDE: (4, 8, 16, 16, 16)
    PRE_NMS_TOP_N_TRAIN: 12000
    # PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    # PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "DetNetSingleConvRPNHead"
  ROI_HEADS:
    USE_FPN: True
    NMS: 0.5
    POST_PROCESS_ON: True
  ROI_BOX_HEAD:
    POOLER: "PSROIPooling"
    POOLER_RESOLUTION: 14
    POOLER_PART_SIZE: 14
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPNDetNetFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 11
    USE_GN: True
  MASK_ON: False
  SEED: 233
DATASETS:
  TRAIN: ("tianchi_xray_with_normal_in_coco",)
  TEST: ("tianchi_xray_eval_no_normal_bbox_in_coco",)
  # TEST: ("tianchi_xray_test_a_in_coco",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (27000, 36000)
  MAX_ITER: 40000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 400
INPUT:
  MIXUP: True
  NO_MIXUP_ITERS: 2000
  VFLIP_PROB_TRAIN: 0.0
  MIN_SIZE_TRAIN: (800, 576, 640, 704, 736, 768, 832, 864, 896, 928, 960)
  PIXEL_MEAN: [0.83102435, 0.83786940, 0.73139444]
  PIXEL_STD: [0.27632148, 0.20124162, 0.29032342]
  TO_BGR255: False
TEST:
  IMS_PER_BATCH: 8
OUTPUT_DIR: "logs/tianchi_xray/mask_rcnn_D_59_FPN_deform_mixup"
