MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "models/share/e2e_mask_rcnn_X_101_32x8d_FPN_1x_without_box_and_mask.pth"
  FORCE_WEIGHT: True
  BACKBONE:
    CONV_BODY: "R-101-D-FPN"
  RESNETS:
    # TRANS_FUNC: "BottleneckWithSyncBN"
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    ASPECT_RATIOS: (0.50, 0.92, 1.50)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    NMS_THRESH: 0.5
    POST_PROCESS_ON: True
  ROI_BOX_HEAD:
    POOLER: "PSROIPooling"
    POOLER_RESOLUTION: 7
    POOLER_PART_SIZE: 7
    POOLER_DEFORM_FC_DIM: 1024
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 11
    USE_GN: False
    CLASS_LOSS_FUNC: "CrossEntropyLoss"
    CLASS_LOSS_SMOOTH_EPS: 0.01
    CLASS_LOSS_SMOOTH_DIST: []
  MASK_ON: False
DATASETS:
  TRAIN: ("tianchi_xray_with_normal_in_coco",)
  TEST: ("tianchi_xray_eval_no_normal_bbox_in_coco",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, 54000)
  MAX_ITER: 60000
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 500
  LR_SCHEDULER: "WarmupCosineAnnealingLR"
INPUT:
  MIXUP: True
  NO_MIXUP_ITERS: 6000
  MIN_SIZE_TRAIN: (800, 576, 640, 704, 736, 768, 832, 864, 896, 928, 960)
  # 0.83102435 0.83786940 0.73139444
  # 0.27632148 0.20124162 0.29032342
  PIXEL_MEAN: [184.026, 211.612, 208.746]
  PIXEL_STD: [74.03, 51.32, 70.46]
  HFLIP_PROB_TRAIN: 0.5
  VFLIP_PROB_TRAIN: 0.0
  HFLIP_PROB_TEST: 0.0
TEST:
  IMS_PER_BATCH: 16
OUTPUT_DIR: "logs/tianchi_xray/mask_rcnn_X_101_32x8d_FPN_deform_mixup"
SEED: 233
PATHS_CATALOG: "tianchi_xray/configs/paths_catalog.py"
